// Code generated by openapi-contract-test-gen; DO NOT EDIT.

package tests

import (
	"net/http"
	"strings"
	"testing"
)

var generatedReadContractCases = []generatedContractCase{
	{
		Name: "list_tasks",
		Method: "GET",
		Path: "/api/tasks",
		SuccessStatus: 200,
		SuccessSchema: generatedContractSchema{Type: "object", Nullable: false, Required: []string{"items", "page", "pageSize", "totalItems", "totalPages"}, Properties: []generatedContractProperty{
			{Name: "items", Schema: generatedContractSchema{Type: "array", Nullable: false, Required: []string{}, Items: &generatedContractSchema{Type: "object", Nullable: false, Required: []string{"createdAt", "description", "id", "state", "title", "updatedAt"}, Properties: []generatedContractProperty{
					{Name: "assigneeId", Schema: generatedContractSchema{Type: "integer", Nullable: true, Required: []string{}}},
					{Name: "boardColumnId", Schema: generatedContractSchema{Type: "integer", Nullable: true, Required: []string{}}},
					{Name: "createdAt", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
					{Name: "description", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
					{Name: "dueAt", Schema: generatedContractSchema{Type: "string", Nullable: true, Required: []string{}}},
					{Name: "id", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
					{Name: "projectId", Schema: generatedContractSchema{Type: "integer", Nullable: true, Required: []string{}}},
					{Name: "state", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
					{Name: "title", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
					{Name: "updatedAt", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
				}}}},
			{Name: "page", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
			{Name: "pageSize", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
			{Name: "totalItems", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
			{Name: "totalPages", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
		}},
		ErrorStatuses: []int{400},
		RequestBodyRequired: false,
		RequestRequiredFields: []string{},
		RequestPropertyTypes: []generatedContractPropertyType{},
		QueryParams: []generatedContractQueryParam{
			{Name: "assigneeId", Type: "integer", Required: false, EnumValues: []string{}},
			{Name: "boardColumnId", Type: "integer", Required: false, EnumValues: []string{}},
			{Name: "page", Type: "integer", Required: false, EnumValues: []string{}},
			{Name: "pageSize", Type: "integer", Required: false, EnumValues: []string{}},
			{Name: "projectId", Type: "integer", Required: false, EnumValues: []string{}},
			{Name: "q", Type: "string", Required: false, EnumValues: []string{}},
			{Name: "state", Type: "string", Required: false, EnumValues: []string{"inbox", "next", "waiting", "scheduled", "done", "someday", "reference"}},
		},
	},
	{
		Name: "list_projects",
		Method: "GET",
		Path: "/api/projects",
		SuccessStatus: 200,
		SuccessSchema: generatedContractSchema{Type: "array", Nullable: false, Required: []string{}, Items: &generatedContractSchema{Type: "object", Nullable: false, Required: []string{"createdAt", "description", "id", "name"}, Properties: []generatedContractProperty{
				{Name: "createdAt", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
				{Name: "description", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
				{Name: "id", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
				{Name: "name", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
			}}},
		ErrorStatuses: []int{},
		RequestBodyRequired: false,
		RequestRequiredFields: []string{},
		RequestPropertyTypes: []generatedContractPropertyType{},
		QueryParams: []generatedContractQueryParam{},
	},
	{
		Name: "list_boards",
		Method: "GET",
		Path: "/api/boards",
		SuccessStatus: 200,
		SuccessSchema: generatedContractSchema{Type: "array", Nullable: false, Required: []string{}, Items: &generatedContractSchema{Type: "object", Nullable: false, Required: []string{"createdAt", "id", "name", "projectId"}, Properties: []generatedContractProperty{
				{Name: "createdAt", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
				{Name: "id", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
				{Name: "name", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
				{Name: "projectId", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
			}}},
		ErrorStatuses: []int{400},
		RequestBodyRequired: false,
		RequestRequiredFields: []string{},
		RequestPropertyTypes: []generatedContractPropertyType{},
		QueryParams: []generatedContractQueryParam{
			{Name: "projectId", Type: "integer", Required: false, EnumValues: []string{}},
		},
	},
	{
		Name: "list_columns",
		Method: "GET",
		Path: "/api/columns",
		SuccessStatus: 200,
		SuccessSchema: generatedContractSchema{Type: "array", Nullable: false, Required: []string{}, Items: &generatedContractSchema{Type: "object", Nullable: false, Required: []string{"boardId", "createdAt", "id", "name", "position"}, Properties: []generatedContractProperty{
				{Name: "boardId", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
				{Name: "createdAt", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
				{Name: "id", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
				{Name: "name", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
				{Name: "position", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
			}}},
		ErrorStatuses: []int{400},
		RequestBodyRequired: false,
		RequestRequiredFields: []string{},
		RequestPropertyTypes: []generatedContractPropertyType{},
		QueryParams: []generatedContractQueryParam{
			{Name: "boardId", Type: "integer", Required: false, EnumValues: []string{}},
		},
	},
	{
		Name: "get_board",
		Method: "GET",
		Path: "/api/boards/{id}",
		SuccessStatus: 200,
		SuccessSchema: generatedContractSchema{Type: "object", Nullable: false, Required: []string{"createdAt", "id", "name", "projectId"}, Properties: []generatedContractProperty{
			{Name: "createdAt", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
			{Name: "id", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
			{Name: "name", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
			{Name: "projectId", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
		}},
		ErrorStatuses: []int{404},
		RequestBodyRequired: false,
		RequestRequiredFields: []string{},
		RequestPropertyTypes: []generatedContractPropertyType{},
		QueryParams: []generatedContractQueryParam{},
	},
}


func TestGeneratedOpenAPIReadContracts(t *testing.T) {
	h := newAPIHarness(t)

	for _, tc := range generatedReadContractCases {
		tc := tc
		t.Run(tc.Name, func(t *testing.T) {
			setup := generatedPrepareReadSetup(t, h, tc.Name)
			path := generatedReadPathWithSetup(tc.Path, setup)
			validPath := generatedPathWithQuery(path, generatedValidQueryValues(tc, setup))

			status, response := generatedJSONRequestAny(h, tc.Method, validPath, nil)
			if status != tc.SuccessStatus {
				t.Fatalf("%s %s: expected success status %d, got %d", tc.Method, tc.Path, tc.SuccessStatus, status)
			}
			generatedAssertSchemaMatch(t, tc.Method+" "+tc.Path+" success", response, tc.SuccessSchema)

			if generatedContainsStatus(tc.ErrorStatuses, http.StatusBadRequest) {
				invalidQuery, ok := generatedInvalidQueryValues(tc)
				if !ok {
					t.Fatalf("%s %s: missing invalid query fixture", tc.Method, tc.Path)
				}
				invalidPath := generatedPathWithQuery(path, invalidQuery)
				status, _ = generatedJSONRequestAny(h, tc.Method, invalidPath, nil)
				if status != http.StatusBadRequest {
					t.Fatalf("%s %s: expected 400 for invalid query, got %d", tc.Method, tc.Path, status)
				}
			}

			if generatedContainsStatus(tc.ErrorStatuses, http.StatusNotFound) && strings.Contains(tc.Path, "{id}") {
				notFoundPath := strings.Replace(tc.Path, "{id}", "9999999", 1)
				status, _ = generatedJSONRequestAny(h, tc.Method, notFoundPath, nil)
				if status != http.StatusNotFound {
					t.Fatalf("%s %s: expected 404 for missing resource, got %d", tc.Method, tc.Path, status)
				}
			}
		})
	}
}
