// Code generated by openapi-contract-test-gen; DO NOT EDIT.

package tests

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"net/url"
	"sort"
	"strings"
	"testing"
)

type generatedContractCase struct {
	Name                  string
	Method                string
	Path                  string
	SuccessStatus         int
	SuccessSchema         generatedContractSchema
	ErrorStatuses         []int
	RequestBodyRequired   bool
	RequestRequiredFields []string
	RequestPropertyTypes  []generatedContractPropertyType
	QueryParams           []generatedContractQueryParam
}

type generatedContractQueryParam struct {
	Name       string
	Type       string
	Required   bool
	EnumValues []string
}

type generatedContractSchema struct {
	Type       string
	Nullable   bool
	Required   []string
	Properties []generatedContractProperty
	Items      *generatedContractSchema
}

type generatedContractProperty struct {
	Name   string
	Schema generatedContractSchema
}

type generatedContractPropertyType struct {
	Name string
	Type string
}

type generatedMutationSetup struct {
	TaskID    int64
	ProjectID int64
	BoardID   int64
	ColumnID  int64
}

var generatedMutationContractCases = []generatedContractCase{
	{
		Name: "create_task",
		Method: "POST",
		Path: "/api/tasks",
		SuccessStatus: 201,
		SuccessSchema: generatedContractSchema{Type: "object", Nullable: false, Required: []string{"createdAt", "description", "id", "state", "title", "updatedAt"}, Properties: []generatedContractProperty{
			{Name: "assigneeId", Schema: generatedContractSchema{Type: "integer", Nullable: true, Required: []string{}}},
			{Name: "boardColumnId", Schema: generatedContractSchema{Type: "integer", Nullable: true, Required: []string{}}},
			{Name: "createdAt", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
			{Name: "description", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
			{Name: "dueAt", Schema: generatedContractSchema{Type: "string", Nullable: true, Required: []string{}}},
			{Name: "id", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
			{Name: "projectId", Schema: generatedContractSchema{Type: "integer", Nullable: true, Required: []string{}}},
			{Name: "state", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
			{Name: "title", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
			{Name: "updatedAt", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
		}},
		ErrorStatuses: []int{400},
		RequestBodyRequired: true,
		RequestRequiredFields: []string{"title"},
		RequestPropertyTypes: []generatedContractPropertyType{
			{Name: "assigneeId", Type: "integer"},
			{Name: "boardColumnId", Type: "integer"},
			{Name: "description", Type: "string"},
			{Name: "dueAt", Type: "string"},
			{Name: "projectId", Type: "integer"},
			{Name: "state", Type: "string"},
			{Name: "title", Type: "string"},
		},
		QueryParams: []generatedContractQueryParam{},
	},
	{
		Name: "patch_task_state",
		Method: "PATCH",
		Path: "/api/tasks/{id}/state",
		SuccessStatus: 200,
		SuccessSchema: generatedContractSchema{Type: "object", Nullable: false, Required: []string{"ok"}, Properties: []generatedContractProperty{
			{Name: "ok", Schema: generatedContractSchema{Type: "boolean", Nullable: false, Required: []string{}}},
		}},
		ErrorStatuses: []int{400},
		RequestBodyRequired: true,
		RequestRequiredFields: []string{"state"},
		RequestPropertyTypes: []generatedContractPropertyType{
			{Name: "actorId", Type: "integer"},
			{Name: "state", Type: "string"},
		},
		QueryParams: []generatedContractQueryParam{},
	},
	{
		Name: "patch_task_board_column",
		Method: "PATCH",
		Path: "/api/tasks/{id}/board-column",
		SuccessStatus: 200,
		SuccessSchema: generatedContractSchema{Type: "object", Nullable: false, Required: []string{"ok"}, Properties: []generatedContractProperty{
			{Name: "ok", Schema: generatedContractSchema{Type: "boolean", Nullable: false, Required: []string{}}},
		}},
		ErrorStatuses: []int{400, 404},
		RequestBodyRequired: true,
		RequestRequiredFields: []string{},
		RequestPropertyTypes: []generatedContractPropertyType{
			{Name: "actorId", Type: "integer"},
			{Name: "boardColumnId", Type: "integer"},
		},
		QueryParams: []generatedContractQueryParam{},
	},
	{
		Name: "create_board",
		Method: "POST",
		Path: "/api/boards",
		SuccessStatus: 201,
		SuccessSchema: generatedContractSchema{Type: "object", Nullable: false, Required: []string{"createdAt", "id", "name", "projectId"}, Properties: []generatedContractProperty{
			{Name: "createdAt", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
			{Name: "id", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
			{Name: "name", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
			{Name: "projectId", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
		}},
		ErrorStatuses: []int{400},
		RequestBodyRequired: true,
		RequestRequiredFields: []string{"name", "projectId"},
		RequestPropertyTypes: []generatedContractPropertyType{
			{Name: "name", Type: "string"},
			{Name: "projectId", Type: "integer"},
		},
		QueryParams: []generatedContractQueryParam{},
	},
	{
		Name: "create_column",
		Method: "POST",
		Path: "/api/columns",
		SuccessStatus: 201,
		SuccessSchema: generatedContractSchema{Type: "object", Nullable: false, Required: []string{"boardId", "createdAt", "id", "name", "position"}, Properties: []generatedContractProperty{
			{Name: "boardId", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
			{Name: "createdAt", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
			{Name: "id", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
			{Name: "name", Schema: generatedContractSchema{Type: "string", Nullable: false, Required: []string{}}},
			{Name: "position", Schema: generatedContractSchema{Type: "integer", Nullable: false, Required: []string{}}},
		}},
		ErrorStatuses: []int{400},
		RequestBodyRequired: true,
		RequestRequiredFields: []string{"boardId", "name"},
		RequestPropertyTypes: []generatedContractPropertyType{
			{Name: "boardId", Type: "integer"},
			{Name: "name", Type: "string"},
			{Name: "position", Type: "integer"},
		},
		QueryParams: []generatedContractQueryParam{},
	},
}


func TestGeneratedOpenAPIMutationContracts(t *testing.T) {
	h := newAPIHarness(t)

	for _, tc := range generatedMutationContractCases {
		tc := tc
		t.Run(tc.Name, func(t *testing.T) {
			setup := generatedPrepareMutationSetup(t, h, tc.Name)
			path := generatedPathWithSetup(tc.Path, setup)
			successBody := generatedSuccessBody(tc.Name, setup)

			status, response := h.jsonRequest(tc.Method, path, successBody)
			if status != tc.SuccessStatus {
				t.Fatalf("%s %s: expected success status %d, got %d", tc.Method, tc.Path, tc.SuccessStatus, status)
			}
			generatedAssertSchemaMatch(t, tc.Method+" "+tc.Path+" success", response, tc.SuccessSchema)

			if generatedContainsStatus(tc.ErrorStatuses, http.StatusBadRequest) {
				invalidBody, ok := generatedInvalidBody(tc)
				if !ok {
					t.Fatalf("%s %s: missing invalid request body fixture", tc.Method, tc.Path)
				}
				status, _ = h.jsonRequest(tc.Method, path, invalidBody)
				if status != http.StatusBadRequest {
					t.Fatalf("%s %s: expected 400 for invalid request, got %d", tc.Method, tc.Path, status)
				}
			}

			if generatedContainsStatus(tc.ErrorStatuses, http.StatusNotFound) {
				notFoundPath := strings.Replace(tc.Path, "{id}", "9999999", 1)
				status, _ = h.jsonRequest(tc.Method, notFoundPath, successBody)
				if status != http.StatusNotFound {
					t.Fatalf("%s %s: expected 404 for missing resource, got %d", tc.Method, tc.Path, status)
				}
			}
		})
	}
}

func generatedPrepareMutationSetup(t *testing.T, h *apiHarness, caseName string) generatedMutationSetup {
	t.Helper()

	switch caseName {
	case "create_task":
		return generatedMutationSetup{}
	case "patch_task_state":
		status, task := h.jsonRequest(http.MethodPost, "/api/tasks", map[string]any{"title": "Contract task"})
		if status != http.StatusCreated {
			t.Fatalf("setup task for state patch: expected 201, got %d", status)
		}
		return generatedMutationSetup{TaskID: mustInt64(t, task["id"])}
	case "patch_task_board_column":
		status, project := h.jsonRequest(http.MethodPost, "/api/projects", map[string]any{"name": "Contract Project"})
		if status != http.StatusCreated {
			t.Fatalf("setup project for board-column patch: expected 201, got %d", status)
		}
		projectID := mustInt64(t, project["id"])

		status, board := h.jsonRequest(http.MethodPost, "/api/boards", map[string]any{"projectId": projectID, "name": "Contract Board"})
		if status != http.StatusCreated {
			t.Fatalf("setup board for board-column patch: expected 201, got %d", status)
		}
		boardID := mustInt64(t, board["id"])

		status, column := h.jsonRequest(http.MethodPost, "/api/columns", map[string]any{"boardId": boardID, "name": "Contract Column", "position": 1})
		if status != http.StatusCreated {
			t.Fatalf("setup column for board-column patch: expected 201, got %d", status)
		}
		columnID := mustInt64(t, column["id"])

		status, task := h.jsonRequest(http.MethodPost, "/api/tasks", map[string]any{"title": "Contract task"})
		if status != http.StatusCreated {
			t.Fatalf("setup task for board-column patch: expected 201, got %d", status)
		}
		return generatedMutationSetup{TaskID: mustInt64(t, task["id"]), ProjectID: projectID, BoardID: boardID, ColumnID: columnID}
	case "create_board":
		status, project := h.jsonRequest(http.MethodPost, "/api/projects", map[string]any{"name": "Contract Project"})
		if status != http.StatusCreated {
			t.Fatalf("setup project for board create: expected 201, got %d", status)
		}
		return generatedMutationSetup{ProjectID: mustInt64(t, project["id"])}
	case "create_column":
		status, project := h.jsonRequest(http.MethodPost, "/api/projects", map[string]any{"name": "Contract Project"})
		if status != http.StatusCreated {
			t.Fatalf("setup project for column create: expected 201, got %d", status)
		}
		projectID := mustInt64(t, project["id"])
		status, board := h.jsonRequest(http.MethodPost, "/api/boards", map[string]any{"projectId": projectID, "name": "Contract Board"})
		if status != http.StatusCreated {
			t.Fatalf("setup board for column create: expected 201, got %d", status)
		}
		return generatedMutationSetup{ProjectID: projectID, BoardID: mustInt64(t, board["id"])}
	default:
		t.Fatalf("unknown generated case %q", caseName)
		return generatedMutationSetup{}
	}
}

func generatedPrepareReadSetup(t *testing.T, h *apiHarness, caseName string) generatedMutationSetup {
	t.Helper()

	status, project := h.jsonRequest(http.MethodPost, "/api/projects", map[string]any{"name": "Read Contract Project"})
	if status != http.StatusCreated {
		t.Fatalf("setup project for %s: expected 201, got %d", caseName, status)
	}
	projectID := mustInt64(t, project["id"])

	status, board := h.jsonRequest(http.MethodPost, "/api/boards", map[string]any{"projectId": projectID, "name": "Read Contract Board"})
	if status != http.StatusCreated {
		t.Fatalf("setup board for %s: expected 201, got %d", caseName, status)
	}
	boardID := mustInt64(t, board["id"])

	status, column := h.jsonRequest(http.MethodPost, "/api/columns", map[string]any{"boardId": boardID, "name": "Read Contract Column", "position": 1})
	if status != http.StatusCreated {
		t.Fatalf("setup column for %s: expected 201, got %d", caseName, status)
	}
	columnID := mustInt64(t, column["id"])

	status, _ = h.jsonRequest(http.MethodPost, "/api/tasks", map[string]any{"title": "Read Contract Task", "projectId": projectID, "boardColumnId": columnID, "state": "inbox"})
	if status != http.StatusCreated {
		t.Fatalf("setup task for %s: expected 201, got %d", caseName, status)
	}

	return generatedMutationSetup{ProjectID: projectID, BoardID: boardID, ColumnID: columnID}
}

func generatedPathWithSetup(path string, setup generatedMutationSetup) string {
	if strings.Contains(path, "{id}") {
		id := setup.TaskID
		if id <= 0 {
			id = 1
		}
		return strings.Replace(path, "{id}", fmt.Sprintf("%d", id), 1)
	}
	return path
}

func generatedReadPathWithSetup(path string, setup generatedMutationSetup) string {
	if !strings.Contains(path, "{id}") {
		return path
	}
	id := int64(1)
	switch {
	case strings.Contains(path, "/api/boards/{id}"):
		if setup.BoardID > 0 {
			id = setup.BoardID
		}
	case strings.Contains(path, "/api/columns/{id}"):
		if setup.ColumnID > 0 {
			id = setup.ColumnID
		}
	default:
		if setup.TaskID > 0 {
			id = setup.TaskID
		}
	}
	return strings.Replace(path, "{id}", fmt.Sprintf("%d", id), 1)
}

func generatedSuccessBody(caseName string, setup generatedMutationSetup) map[string]any {
	switch caseName {
	case "create_task":
		return map[string]any{"title": "Contract task"}
	case "patch_task_state":
		return map[string]any{"state": "inbox"}
	case "patch_task_board_column":
		return map[string]any{"boardColumnId": setup.ColumnID}
	case "create_board":
		return map[string]any{"projectId": setup.ProjectID, "name": "Contract Board"}
	case "create_column":
		return map[string]any{"boardId": setup.BoardID, "name": "Contract Column", "position": 1}
	default:
		return map[string]any{}
	}
}

func generatedValidQueryValues(tc generatedContractCase, setup generatedMutationSetup) map[string]string {
	query := map[string]string{}
	for _, param := range tc.QueryParams {
		switch param.Name {
		case "page":
			query[param.Name] = "1"
		case "pageSize":
			query[param.Name] = "20"
		case "state":
			if len(param.EnumValues) > 0 {
				query[param.Name] = param.EnumValues[0]
			} else {
				query[param.Name] = "inbox"
			}
		case "projectId":
			if setup.ProjectID > 0 {
				query[param.Name] = fmt.Sprintf("%d", setup.ProjectID)
			} else {
				query[param.Name] = "1"
			}
		case "boardId":
			if setup.BoardID > 0 {
				query[param.Name] = fmt.Sprintf("%d", setup.BoardID)
			} else {
				query[param.Name] = "1"
			}
		case "boardColumnId":
			if setup.ColumnID > 0 {
				query[param.Name] = fmt.Sprintf("%d", setup.ColumnID)
			} else {
				query[param.Name] = "1"
			}
		case "q", "assigneeId":
		default:
			switch param.Type {
			case "integer", "number":
				query[param.Name] = "1"
			case "boolean":
				query[param.Name] = "true"
			case "string":
				if len(param.EnumValues) > 0 {
					query[param.Name] = param.EnumValues[0]
				} else {
					query[param.Name] = "value"
				}
			}
		}
	}
	return query
}

func generatedInvalidQueryValues(tc generatedContractCase) (map[string]string, bool) {
	params := append([]generatedContractQueryParam(nil), tc.QueryParams...)
	sort.Slice(params, func(i, j int) bool { return params[i].Name < params[j].Name })

	for _, param := range params {
		switch param.Type {
		case "integer", "number", "boolean":
			return map[string]string{param.Name: "invalid"}, true
		case "string":
			if len(param.EnumValues) > 0 {
				return map[string]string{param.Name: "invalid"}, true
			}
		}
	}

	return nil, false
}

func generatedPathWithQuery(path string, query map[string]string) string {
	if len(query) == 0 {
		return path
	}
	keys := make([]string, 0, len(query))
	for key := range query {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	values := url.Values{}
	for _, key := range keys {
		values.Set(key, query[key])
	}
	encoded := values.Encode()
	if encoded == "" {
		return path
	}
	if strings.Contains(path, "?") {
		return path + "&" + encoded
	}
	return path + "?" + encoded
}

func generatedInvalidBody(tc generatedContractCase) (map[string]any, bool) {
	if len(tc.RequestRequiredFields) > 0 {
		return map[string]any{}, true
	}

	props := append([]generatedContractPropertyType(nil), tc.RequestPropertyTypes...)
	sort.Slice(props, func(i, j int) bool { return props[i].Name < props[j].Name })
	for _, prop := range props {
		switch prop.Type {
		case "integer", "number":
			return map[string]any{prop.Name: "invalid"}, true
		case "string":
			return map[string]any{prop.Name: 123}, true
		case "boolean":
			return map[string]any{prop.Name: "invalid"}, true
		}
	}

	if tc.RequestBodyRequired {
		return nil, true
	}
	return nil, false
}

func generatedContainsStatus(statuses []int, target int) bool {
	for _, status := range statuses {
		if status == target {
			return true
		}
	}
	return false
}

func generatedJSONRequestAny(h *apiHarness, method, path string, body any) (int, any) {
	h.t.Helper()

	var reader *bytes.Reader
	if body == nil {
		reader = bytes.NewReader(nil)
	} else {
		payload, err := json.Marshal(body)
		if err != nil {
			h.t.Fatalf("marshal request body: %v", err)
		}
		reader = bytes.NewReader(payload)
	}

	req := httptest.NewRequest(method, path, reader)
	req.Header.Set("Content-Type", "application/json")
	rr := httptest.NewRecorder()
	h.h.ServeHTTP(rr, req)

	var out any
	_ = json.NewDecoder(rr.Body).Decode(&out)
	if out == nil {
		out = map[string]any{}
	}
	return rr.Code, out
}

func generatedAssertSchemaMatch(t *testing.T, context string, value any, schema generatedContractSchema) {
	t.Helper()

	if value == nil {
		if schema.Nullable {
			return
		}
		t.Fatalf("%s: expected %s, got null", context, schema.Type)
	}

	switch schema.Type {
	case "object":
		obj, ok := value.(map[string]any)
		if !ok {
			t.Fatalf("%s: expected object, got %T", context, value)
		}
		for _, key := range schema.Required {
			if _, exists := obj[key]; !exists {
				t.Fatalf("%s: missing required property %q", context, key)
			}
		}
		for _, prop := range schema.Properties {
			v, exists := obj[prop.Name]
			if !exists {
				continue
			}
			generatedAssertSchemaMatch(t, context+"."+prop.Name, v, prop.Schema)
		}
	case "array":
		arr, ok := value.([]any)
		if !ok {
			t.Fatalf("%s: expected array, got %T", context, value)
		}
		if schema.Items != nil {
			for i, item := range arr {
				generatedAssertSchemaMatch(t, fmt.Sprintf("%s[%d]", context, i), item, *schema.Items)
			}
		}
	case "integer", "number":
		if _, ok := value.(float64); !ok {
			t.Fatalf("%s: expected number, got %T", context, value)
		}
	case "string":
		if _, ok := value.(string); !ok {
			t.Fatalf("%s: expected string, got %T", context, value)
		}
	case "boolean":
		if _, ok := value.(bool); !ok {
			t.Fatalf("%s: expected boolean, got %T", context, value)
		}
	default:
		t.Fatalf("%s: unsupported schema type %q", context, schema.Type)
	}
}
